### ISSUE TITLE
No errors but no outputs?

### ISSUE THREAD

**Issue by angelaparodymerino** [mourisl/Rcorrector#17]
Hi,

It is the first time I am using this pipeline.

I run:

`$ perl run_rcorrector.pl -1 /home/mcv/data/RNAseq_PRJNA338760/FastQrawRNAseq/SRR4030251_1.fastq -2 /home/mcv/data/RNAseq_PRJNA338760/FastQrawRNAseq/SRR4030251_2.fastq -od RNAseqCorrected`

only using my first RNAseq sample (SRR4030251) and specifying an output firectory with -od named RNAseqCorrected. No outputs were created (I found folder empty) but it seems that the pipeline worked without errors:

```
Put the kmers into bloom filter
/home/mcv/angela/rcorrector/jellyfish/bin/jellyfish bc -m 23 -s 100000000 -C -t 1 -o tmp_25a827cbe7550788dca189b0e261612e.bc /home/mcv/data/RNAseq_PRJNA338760/FastQrawRNAseq/SRR4030251_1.fastq /home/mcv/data/RNAseq_PRJNA338760/FastQrawRNAseq/SRR4030251_2.fastq 
Count the kmers in the bloom filter
/home/mcv/angela/rcorrector/jellyfish/bin/jellyfish count -m 23 -s 100000 -C -t 1 --bc tmp_25a827cbe7550788dca189b0e261612e.bc -o tmp_25a827cbe7550788dca189b0e261612e.mer_counts /home/mcv/data/RNAseq_PRJNA338760/FastQrawRNAseq/SRR4030251_1.fastq /home/mcv/data/RNAseq_PRJNA338760/FastQrawRNAseq/SRR4030251_2.fastq 
Dump the kmers
/home/mcv/angela/rcorrector/jellyfish/bin/jellyfish dump -L 2 tmp_25a827cbe7550788dca189b0e261612e.mer_counts > tmp_25a827cbe7550788dca189b0e261612e.jf_dump
Error correction
/home/mcv/angela/rcorrector/rcorrector -od RNAseqCorrected  -p /home/mcv/data/RNAseq_PRJNA338760/FastQrawRNAseq/SRR4030251_1.fastq /home/mcv/data/RNAseq_PRJNA338760/FastQrawRNAseq/SRR4030251_2.fastq -c tmp_25a827cbe7550788dca189b0e261612e.jf_dump
Stored 12435946 kmers
Weak kmer threshold rate: 0.002239 (estimated from 0.950/1 of the chosen kmers)
Bad quality threshold is '#'
Processed 30654092 reads
	Corrected 12790708 bases.
```

The output directory is inside the folder with the input files, and I double check that the name if this ouput folder is indeed RNAseqCorrected. Any idea of why outputs are not being created?

Thanks in advance,

'Angela

**Comment by mourisl** [comment]
Is it the case that the files SRR4030251_*.cor.fastq are not in the folder or the files are there but they are empty? Thanks.

**Comment by angelaparodymerino** [comment]
Thanks for the answer.

The case is that the files SRR4030251_*.cor.fastq are not in the folder. In short, output folder is empty.

Regards,

'Angela

**Comment by angelaparodymerino** [comment]
Problem solved. I thought I had to create a folder in advance, but that run created a folder inside the folder where Rcorrector is. I found that folder with the *.cor.fastq files. All good.
