### ISSUE TITLE
make fatal error: no zlib.h

### ISSUE THREAD

**Issue by e1992** [mourisl/Rcorrector#20]
Hi, 
 When I run make I get the following error. 
`g++ -Wall -O3 -std=c++0x   -c -o main.o main.cpp
In file included from main.cpp:12:0:
Reads.h:7:10: fatal error: zlib.h: No such file or directory
 #include <zlib.h>
          ^~~~~~~~
compilation terminated.
make: *** [<builtin>: main.o] Error 1`

what is zlib.h? I'm not sure where it should be or how to fix this. 

Thanks for your help!!

**Comment by mourisl** [comment]
This is the header file to parse compressed file, which usually comes with the system. You may need install zlib first.
