### ISSUE TITLE
Running jellyfish2

### ISSUE THREAD

**Issue by 000generic** [mourisl/Rcorrector#21]
In contrast to Rcorrector GitHub directions, Rcorrector usage info at the command line seems to indicate I should first run Jellyfish2 on my reads (-c parameter). 

Usage: ./rcorrector [OPTIONS]
OPTIONS:
Required parameters:
        -r seq_file: seq_file is the path to the sequence file. Can use multiple -r to specifiy multiple sequence files
        -p seq_file_left seq_file_right: the paths to the paired-end data set. Can use multiple -p to specifiy multiple sequence files
        -i seq_file: seq_file is the path to the interleaved mate-pair sequence file. Can use multiple -i
        -c jf_dump: the kmer counts dumped by JellyFish
        -k kmer_length

If this is correct, do you have an example of command line settings I might use to run Jellyfish2? Also, is there a suggested method for determining the value to provide for -k ?  

Thank you!

**Comment by mourisl** [comment]
You should run rcorrector through the wrapper "perl run_rcorrector.pl". Jellyfish and other parts are all handled there.

**Comment by 000generic** [comment]
Works great!  Thank you for such a quick response :)
Eric
