### ISSUE TITLE
more reads after correction?

### ISSUE THREAD

**Issue by smallfishcui** [mourisl/Rcorrector#22]
Hi,

I used the command : run_rcorrector.pl -t 4 -1 A1.1.fastq.gz -2 A1.2.fastq.gz 
The program is still running, but when i check the A1.1.cor.fq.gz, it's already bigger than the original file, 
grep -c "@" A1.1.fastq.gz
17032759
grep -c "@" A1.1.cor.fq.gz
19037768
Is it supposed to be like this? Where do the extra reads come from?

Thanks,
Cui

**Comment by mourisl** [comment]
Yes, Rcorrector writes some extra information on the description line, such as whether this read can be corrected, some simple statistics about its kmer count. Rcorrector also uses level 1 compression (faster compression but takes larger space), so the output file could be larger than the original gzipped file if it is compressed with a higher level.

**Comment by smallfishcui** [comment]
Okay. Thank you for the answer! It's not an issue any more, I will close it.
