### ISSUE TITLE
(Also) Fails at Stage 3  

### ISSUE THREAD

**Issue by jrede** [mourisl/Rcorrector#24]
Hi! I'm trying to run the example data before running my own, but it fails at stage 3. Thank you for any help!

After running 'make':

g++ -Wall -O3 -std=c++0x   -c -o main.o main.cpp
main.cpp:132:9: warning: unused variable 'j' [-Wunused-variable]
        int i, j, k ;
               ^
In file included from main.cpp:14:
./Store.h:20:11: warning: private field 'size' is not used
      [-Wunused-private-field]
        uint64_t size ;
                 ^
2 warnings generated.
g++ -Wall -O3 -std=c++0x   -c -o KmerCode.o KmerCode.cpp
g++ -Wall -O3 -std=c++0x   -c -o ErrorCorrection.o ErrorCorrection.cpp
ErrorCorrection.cpp:75:6: warning: unused variable 'i' [-Wunused-variable]
        int i, ind ;
            ^
ErrorCorrection.cpp:395:7: warning: unused variable 'j' [-Wunused-variable]
                int j, k ;
                    ^
In file included from ErrorCorrection.cpp:1:
In file included from ./ErrorCorrection.h:8:
./Store.h:20:11: warning: private field 'size' is not used
      [-Wunused-private-field]
        uint64_t size ;
                 ^
3 warnings generated.
g++ -o rcorrector -Wall -O3 -std=c++0x KmerCode.o ErrorCorrection.o main.o -I . -lpthread -lz 
if [ ! `which jellyfish` ] || [ `jellyfish --version | cut -f2 -d' ' | cut -f1 -d'.'` -ne 2 ] ; \
	then \
		if [ ! -f ./jellyfish/bin/jellyfish ] ; \
		then \
			wget -O jellyfish.tar.gz https://github.com/gmarcais/Jellyfish/releases/download/v2.2.4/jellyfish-2.2.4.tar.gz ;\
			tar -xzf jellyfish.tar.gz ; mv jellyfish-2.2.4 jellyfish ; rm jellyfish.tar.gz ; cd jellyfish && ./configure && make ;\
		fi;\
	fi ;

After running 'perl run_rcorrector.pl -1 Sample/sample_read1.fq -2 Sample/sample_read2.fq'

Put the kmers into bloom filter
jellyfish bc -m 23 -s 100000000 -C -t 1 -o tmp_ace52f5f95f6aca4902485770ae3303d.bc Sample/sample_read1.fq Sample/sample_read2.fq 
Count the kmers in the bloom filter
jellyfish count -m 23 -s 100000 -C -t 1 --bc tmp_ace52f5f95f6aca4902485770ae3303d.bc -o tmp_ace52f5f95f6aca4902485770ae3303d.mer_counts Sample/sample_read1.fq Sample/sample_read2.fq 
Dump the kmers
jellyfish dump -L 2 tmp_ace52f5f95f6aca4902485770ae3303d.mer_counts > tmp_ace52f5f95f6aca4902485770ae3303d.jf_dump
Error correction
/Volumes/REDE_Seagate/data/Pair-end data (fasterq-dump)/rcorrector/rcorrector   -p Sample/sample_read1.fq Sample/sample_read2.fq -c tmp_ace52f5f95f6aca4902485770ae3303d.jf_dump
sh: -c: line 0: syntax error near unexpected token `('
sh: -c: line 0: `/Volumes/REDE_Seagate/data/Pair-end data (fasterq-dump)/rcorrector/rcorrector   -p Sample/sample_read1.fq Sample/sample_read2.fq -c tmp_ace52f5f95f6aca4902485770ae3303d.jf_dump'
Failed at stage 3.

**Comment by mourisl** [comment]
It seems this is caused by the parenthesis in the path. Can you change the folder name or add Rcorrector to $PATH? Thanks.

**Comment by jrede** [comment]
Awesome! Thank you!
