### ISSUE TITLE
rm: cannot remove file, no such file or directory--is this an error?

### ISSUE THREAD

**Issue by peanut-buddy** [mourisl/Rcorrector#26]
Hello! 

I am new to using Rcorrector. I noticed in the output of some files, the job seems to have completed successfully (reads were processed and corrected) but I noticed the rm error and was wondering if that's typical, or did the program did not complete?

Thank you!

From the output file:
Processed 22401462 reads
        Corrected 4048538 bases.
rm: cannot remove 'tmp_34047852011a711e1950ffddb6b6ccd2.bc': No such file or directory
rm: cannot remove 'tmp_34047852011a711e1950ffddb6b6ccd2.mer_counts': No such file or directory
rm: cannot remove 'tmp_34047852011a711e1950ffddb6b6ccd2.jf_dump': No such file or directory

**Comment by mourisl** [comment]
What was your running command and other output on the screen?  Thanks.

**Comment by peanut-buddy** [comment]
I ran the command like this: run_rcorrector.pl -1 ${i}_1.fastq -2 ${i}_2.fastq -od ${i}_rcor
(in the main directory where the fastq files are stored)

Here is the output on the screen from the output I noticed the rm error:

Put the kmers into bloom filter
jellyfish bc -m 23 -s 100000000 -C -t 1 -o tmp_5f496c2d20c7b4420ddb8aabd4d939aa.bc Photuris.frontalis_SRR2104391_Head_M_1.fastq Photuris.frontalis_SRR2104391_Head_M_2.fastq 
Count the kmers in the bloom filter
jellyfish count -m 23 -s 100000 -C -t 1 --bc tmp_5f496c2d20c7b4420ddb8aabd4d939aa.bc -o tmp_5f496c2d20c7b4420ddb8aabd4d939aa.mer_counts Photuris.frontalis_SRR2104391_Head_M_1.fastq Photuris.frontalis_SRR2104391_Head_M_2.fastq 
Dump the kmers
jellyfish dump -L 2 tmp_5f496c2d20c7b4420ddb8aabd4d939aa.mer_counts > tmp_5f496c2d20c7b4420ddb8aabd4d939aa.jf_dump
Error correction
/usr/local/apps/eb/Rcorrector/1.0.2-foss-2016b/bin/rcorrector -od Photuris.frontalis_SRR2104391_Head_M_rcor  -p Photuris.frontalis_SRR2104391_Head_M_1.fastq Photuris.frontalis_SRR2104391_Head_M_2.fastq -c tmp_5f496c2d20c7b4420ddb8aabd4d939aa.jf_dump
Stored 54053926 kmers
Weak kmer threshold rate: 0.003575 (estimated from 0.950/1 of the chosen kmers)
Bad quality threshold is 9
Processed 22746012 reads
        Corrected 6963497 bases.
rm: cannot remove 'tmp_5f496c2d20c7b4420ddb8aabd4d939aa.bc': No such file or directory
rm: cannot remove 'tmp_5f496c2d20c7b4420ddb8aabd4d939aa.mer_counts': No such file or directory
rm: cannot remove 'tmp_5f496c2d20c7b4420ddb8aabd4d939aa.jf_dump': No such file or directory


Here's the output of a run that seemed fine:

Put the kmers into bloom filter
jellyfish bc -m 23 -s 100000000 -C -t 1 -o tmp_5f496c2d20c7b4420ddb8aabd4d939aa.bc Photuris.frontalis_SRR2104391_Head_M_1.fastq Photuris.frontalis_SRR2104391_Head_M_2.fastq 
Count the kmers in the bloom filter
jellyfish count -m 23 -s 100000 -C -t 1 --bc tmp_5f496c2d20c7b4420ddb8aabd4d939aa.bc -o tmp_5f496c2d20c7b4420ddb8aabd4d939aa.mer_counts Photuris.frontalis_SRR2104391_Head_M_1.fastq Photuris.frontalis_SRR2104391_Head_M_2.fastq 
Dump the kmers
jellyfish dump -L 2 tmp_5f496c2d20c7b4420ddb8aabd4d939aa.mer_counts > tmp_5f496c2d20c7b4420ddb8aabd4d939aa.jf_dump
Error correction
/usr/local/apps/eb/Rcorrector/1.0.2-foss-2016b/bin/rcorrector -od Photuris.frontalis_SRR2104391_Head_M_rcor  -p Photuris.frontalis_SRR2104391_Head_M_1.fastq Photuris.frontalis_SRR2104391_Head_M_2.fastq -c tmp_5f496c2d20c7b4420ddb8aabd4d939aa.jf_dump
Stored 54053926 kmers
Weak kmer threshold rate: 0.003575 (estimated from 0.950/1 of the chosen kmers)
Bad quality threshold is 9
Processed 22746012 reads
        Corrected 6963497 bases.

Could have it have deleted the intermediate files before the other R2 had finished, if so, would this affect the output?
Thank you!

**Comment by mourisl** [comment]
Did you run rcorrector on the same files at the same time? So the intermediate files got removed by other runs. Since the output of “Corrected XXX bases” showed the same value I don't  think the results were affected though.

**Comment by peanut-buddy** [comment]
I did run the all the files at the same time. Thank you for helping me figure this out!!
