### ISSUE TITLE
jellyfish error

### ISSUE THREAD

**Issue by etihelka** [mourisl/Rcorrector#32]
Hi, 

Apologies for what may be a naive question. When trying to run rCorrector, I get this error message: 

```
Put the kmers into bloom filter
/cm/shared/apps/Rcorrector-2021/Rcorrector/jellyfish/bin/jellyfish bc -m 23 -s 100000000 -C -t 1 -o tmp_0ddc4b88cb8a06ba2dc8258055a121fc.bc SRR2083633_1_trimmed.fastq SRR2083633_2_trimmed.fastq
/usr/bin/ld: cannot open output file /cm/shared/apps/Rcorrector-2021/Rcorrector/jellyfish/bin/.libs/83205-lt-jellyfish: Permission denied
collect2: error: ld returned 1 exit status
Failed at stage 0.
```

My command was: 

`perl /cm/shared/apps/Rcorrector-2021/Rcorrector/run_rcorrector.pl -1 SRR2083633_1_trimmed.fastq -2 SRR2083633_2_trimmed.fastq`

I tried reinstalling to get the latest version of rCorrector (v 1.0.4), but the issue still persists.

**Comment by mourisl** [comment]
It seems you don't have the access permission to the jellyfish's dynamic-linked library. I think you may need to download rcorrector's source code and run "make" to build the executables with your own permission.

**Comment by ertihelka** [comment]
Thank you, I will give it a go.

**Comment by etihelka** [comment]
It was indeed an issue with permissions on our cluster. The IT changed it and it runs OK now.
