### ISSUE TITLE
The -trim option

### ISSUE THREAD

**Issue by StevenWingett** [mourisl/Rcorrector#34]
Hi,

Firstly, thank you for making this great tool available to the bioinformatics community.  I have a question about the -trim option.  It is mentioned in the README.md file:

-trim : allow trimming (default: false)

But this option is not present in the run_rcorrector.pl help message, nor is this option allowed by the this script.

I presume that the run_rcorrector.pl  script has changed but the README.md has not been updated accordingly.  I was just wondering, does this mean that the tool will accept quality-trimmed FASTQ files by default?

Many thanks for your assistance.

Regards,
Steven

**Comment by mourisl** [comment]
Thanks for finding this error! The trim feature is removed because it may remove valuable information for lowly expressed transcripts. I have updated the README flie.

Rcorrector can take fastqs with varied read length, so you can directly use quality-trimmed FASTQ file as input.

**Comment by StevenWingett** [comment]
Great, thanks for letting me know.

Steven
