### ISSUE TITLE
Feature Request: Argument for controlling where temporary files are written

### ISSUE THREAD

**Issue by gladshire** [mourisl/Rcorrector#40]
If I am mistaken, and this is currently already possible, I apologize.

I would like to integrate Rcorrector into a transcriptome assembly pipeline, and I think allowing specification of where Rcorrector should place the temporary files generated during its runtime (.bc / .mer_counts / .jf_dump), rather than placing them in the current working directory, would be a nice quality of life feature to add.

**Comment by mourisl** [comment]
I just added the option "-tmpd" that can specify the directory for storing temporary files (need to manually create the folder first). Please let me whether it works on your data. Thank you!

**Comment by gladshire** [comment]
Works great! Would this be something you'd be willing to publish a new set of pre-compiled binaries for? Totally understand if not.

**Comment by mourisl** [comment]
I have released a new version 1.0.7. The bioconda will automatically update rcorrector soon and will generate the pre-compiled binaries at: https://anaconda.org/bioconda/rcorrector/files

**Comment by gladshire** [comment]
Much appreciated, along with your promptness with everything.
