### ISSUE TITLE
Rcorrector produces malformed corrected FASTQ file

### ISSUE THREAD

**Issue by patrickaoude** [mourisl/Rcorrector#41]
Hi, thanks for your continued work on Rcorrector. I am having an issue using the tool on my FASTQ sample. At first I thought it was potentially due to multiple threads/processes writing to the output at the same time, but I found running in single-threaded mode I still have the same issue. I am using the latest Rcorrector version (1.0.7) and am providing a single FASTQ file (nanopore long reads). I have tried it with a subset of the FASTQ file just for the sake of time, and I find that while the initial entries appear fine, at some point the contents become malformed, especially with the appearance of multiple plus lines (+) one after another. I've tried the command on a linux-based server/cluster environment and also locally on macOS Sonoma (14.5, M2 MacBook Pro). Both produce the same issue.

Here is my command:

`perl run_rcorrector.pl -s ~/Downloads/starfish_long_reads_test.part_001.fastq -t 1 -od ~/Downloads`

Then I view the output:

`less -N ~/Downloads/starfish_long_reads_test.part_001.cor.fq`

And the malformed lines appear as early as line 48 with the introduction of two + lines rather than the standard single line. I also see the issue if I output the results to stdout.

Another note, I don't see the same error when I test the exact same code with sample_read1 provided in the Rcorrector download. So perhaps there is something specific about my FASTQ file that is causing the errors that I'm not aware of.

I've attached both the input and output files: [sample.zip](https://github.com/user-attachments/files/16444087/sample.zip)

**Comment by mourisl** [comment]
Rcorrector is designed for short-read error correction, and there is a limit on the read length of 1024. The error happens to a read with a length of 1593 that will trigger a bug.
