### ISSUE TITLE
Drop bundled jellyfish-2.1.3.tar.gz copy from GIT tree

### ISSUE THREAD

**Issue by mmokrejs** [mourisl/Rcorrector#6]
Hi,
  I appreciate your efforts to make it easy for users but including a copy of jellyfish is not the way to go. I would like to prepare a package for Gentoo Linux but the snapshot will just be unnecessarily large. also, jellyfish has a different license so it is not fair from this perspective either.

  I propose to change the Makefile to run a simple wget to fetch the tarball, ideally only if check for `which jellyfish' fails. Or even better, if you just improve an error message in the perl wrapper if jellyfish cannot be found in $PATH.

Thank you
Martin

**Comment by mourisl** [comment]
Using wget is a great idea! I've implemented your idea into the Makefile and removed the tar file from the repository. Thanks.
