### ISSUE TITLE
unable to find/install prerequisite modules

### ISSUE THREAD

**Issue by minor7b5** [mourisl/Rcorrector#8]
Please forgive any ignorance about sys admin in this question, my expertise in loading modules, etc is lacking.

I have been attempting to run Rcorrecter but I get the following error message:

Can't locate Digest/MD5.pm in @INC (@INC contains: /usr/local/lib64/perl5 /usr/local/share/perl5 /usr/lib64/perl5/vendor_perl /usr/share/perl5/vendor_perl /usr/lib64/perl5 /usr/share/perl5 .)

I presume this is because I am missing the prerequisite module 5.10.1-fasrc04 in my system? Could you please provide me with some direction of how I can install this into my system? I have access to cpanm and sudo privileges.

Many thanks,
Ali

**Comment by mourisl** [comment]
You can run the command with the "sudo":
perl -MCPAN -e "shell"
> install Digest::MD5

Please let me know how this works out.

Li

**Comment by minor7b5** [comment]
Dear Li,

Thank you so much for this - took 30 seconds to fix! It does indeed appear to be working now.

However, the machine I have sudo access to only has 8 cores and 30GB RAM, so I fear it may not be able to handle Rcorrect. I will get a system admin to install MD5 on the local cluster asap though, it helps to know what the missing module was called.

Many thanks,
Ali

**Comment by mourisl** [comment]
Rcorrector takes about 5GB on human data set with 100M reads, I think 30GB RAM should be enough.

**Comment by minor7b5** [comment]
Thank you very much, it worked perfectly.
A
